#############################  Display  #############################
# Use error level to only show failed requests
verbose = "error"
# Don't show interactive progress bar while checking links.
no_progress = true
# Don't show the source file of links
no_show_source = true

#############################  Requests  ############################
# URL remapping rules.
remap = [
    # First handle the resource paths relative to pages directory
    "file:///(.*?)/img/(.*) file:///./$1/public/img/$2", 
    "file:///(.*?)/icons/(.*) file:///./$1/public/icons/$2", 
    "file:///(.*?)/resources/(.*) file:///./$1/public/resources/$2", 
    "file:///(.*?)/audit-reports/(.*) file:///./$1/public/audit-reports/$2", 
    # Then handle the internal links for mdx files
    "file:///([^#.?]+)(#.*)?$ file:///./pages/$1.mdx$2",
    "\\\\& &"
]

# Base URL or website root directory to check relative URLs
base = "."

#############################  Exclusions  ##########################
# Exclude loopback IP address range and localhost from checking.
exclude_loopback = true
# Exclude all mail addresses from checking.
exclude_mail = true
# Exclude RPC URLs from checking.
exclude = [
    'https://mainnet.optimism.io',
    'https://mainnet-sequencer.optimism.io',
    'https://sepolia.optimism.io',
    'https://sepolia-sequencer.optimism.io',
    'https://archive.org',
    'https://web.archive.org',
    'https://mainnet.base.org',
    'https://sepolia.base.org',
    'https://optimism.easscan.org',
    '\.(pdf|zip|png|jpg|jpeg|gif|svg)$'
]

# Accept all status codes except 404
accept = [
    "100..=399",
    "401..=403",
    "405..=999"
]

# Use compact format for cleaner output
format = "compact"